import { NgModule } from '@angular/core';

import {
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatTabsModule,
  MatSidenavModule,
  MatListModule,
  MatIconModule,
  MatToolbarModule,
  MatMenuModule,
  MatTableModule,
  MatSelectModule,
  MatGridListModule,
  MatFormFieldModule,
  MatRadioModule,
  MatSnackBarModule,
  MatCheckboxModule,
  MatSlideToggleModule,
  MatTooltipModule,
  MatDatepickerModule,
  MatDialogModule,
  MatNativeDateModule,
  MatProgressSpinnerModule,
  MatRippleModule,
  MatSortModule,
  MatCommonModule
} from '@angular/material';
import {MatPaginatorModule} from '@angular/material/paginator';
import { MatMomentDateModule } from '@angular/material-moment-adapter';
import {MatProgressBarModule} from '@angular/material/progress-bar';

@NgModule({
  declarations: [],
  imports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatTabsModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatTableModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatRadioModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatDatepickerModule,
    MatDialogModule,
    MatNativeDateModule,
    MatMomentDateModule,
    MatRippleModule,
    MatSidenavModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressBarModule,
    MatCommonModule,
  ],
  exports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatTabsModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatTableModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatRadioModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatDatepickerModule,
    MatDialogModule,
    MatNativeDateModule,
    MatMomentDateModule,
    MatRippleModule,
    MatSidenavModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressBarModule
  ],
  providers: [
  ]
})
export class MaterialModule {}
